services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # backend
  nodejs:
    build: ./nodejs
    container_name: nodejs
    ports:
      - "5000:5000"
    volumes:
    - ./nodejs:/app
    - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  # frontend
  react:
    build: ./react
    container_name: react
    ports:
      - "5173:5173"
    volumes:
    - ./react:/app
    - /app/node_modules
    depends_on:
    - nodejs

volumes:
  mongo-data: